org.gradle.jvmargs = -Xmx3G
org.gradle.daemon = false

# Common metadata
mod_license = MIT
mod_sources = https://github.com/Engine-Room/Flywheel
mod_issues = https://github.com/Engine-Room/Flywheel/issues
mod_homepage = https://github.com/Engine-Room/Flywheel
# Flywheel metadata
flywheel_id=flywheel
flywheel_name=Flywheel
flywheel_version=1.0.6-beta
flywheel_description=An overhauled entity and block entity rendering API.
# Vanillin metadata
vanillin_id=vanillin
vanillin_name=Vanillin
vanillin_version=1.1.3
vanillin_description=Instanced rendering for entities and block entities via Flywheel.
# Vanillin dependencies
flywheel_maven_version_range=[1.0.0,2.0)
flywheel_semver_version_range=>=1.0.0 <2.0.0

# Mod dependency declarations
minecraft_semver_version_range = 1.21.11
minecraft_maven_version_range = [1.21.11]
fabric_api_version_range = >=0.139.4
neoforge_version_range = [21.11.0-beta,)

# General build dependency versions
java_version = 21
arch_loom_version = 1.13.467
parchment_minecraft_version = 1.21.10
parchment_version = 2025.10.12

# Minecraft build dependency versions
minecraft_version = 1.21.11
neoforge_version = 21.11.0-beta
fabric_loader_version = 0.18.2
fabric_api_version = 0.139.4+1.21.11

# Build dependency mod versions
enable_sodium_and_iris = false
sodium_version = mc1.21.11-0.8.0
iris_version = 1.10.0+1.21.11

# Publication info
flywheel_group=dev.engine-room.flywheel
vanillin_group=dev.engine-room.vanillin
artifact_minecraft_version = 1.21.11
