name: Bug Report
description: Create a bug report to help us improve Flywheel
labels: [ "bug" ]
body:
    -   type: textarea
        attributes:
            label: Describe the Bug
            description: A clear and concise description of what the bug is
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Reproduction Steps
            description: Tell us about the steps to reproduce the bug
            value: |
                1.
                2.
                3.
                ...
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Expected Result
            description: A clear and concise description of what you expected to happen
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Screenshots and Videos
            description: If applicable, add screenshots or videos to help explain your problem
        validations:
            required: false
    -   type: input
        attributes:
            label: Crash Report or Log
            description: If applicable, please add a link to the crash report or log that was created when this issue occured
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "*[Pastebin](https://pastebin.com/) is standard.*"
    -   type: input
        attributes:
            label: Operating System
            description: The operating system you were using when the bug occured
            placeholder: Windows 11
        validations:
            required: true
    -   type: input
        attributes:
            label: What is your GPU?
            description: Enter the vendor and model of the GPU you were using when the bug occured
            placeholder: Nvidia GeForce RTX 3060
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Mod Version
            description: The version of the mod you were using when the bug occured
            options:
                - "0.6.10"
                - "0.6.9"
                - "0.6.8.a"
                - "0.6.8"
                - "0.6.7"
                - "0.6.6"
                - "0.6.5"
                - "0.6.4"
                - "0.6.3"
                - "0.6.2"
                - "0.6.1"
                - "0.6.0"
                - "0.5.1"
                - "0.5.0a"
                - "0.5.0"
                - "0.4.2-rc"
                - "0.4.1"
                - "0.4.0"
                - "0.3.0"
                - "0.2.5"
                - "0.2.4"
                - "0.2.3"
                - "0.2.2"
                - "0.2.1"
                - "0.2.0"
                - "0.1.1"
                - "0.1.0"
                - "0.0.3"
                - "0.0.2"
                - "0.0.1"
        validations:
            required: true
    -   type: dropdown
        attributes:
            label: Minecraft Version
            description: The version of Minecraft you were using when the bug occured
            options:
                - "1.20.4"
                - "1.20.1"
                - "1.19.2"
                - "1.18.2"
                - "1.18.1"
                - "1.18"
                - "1.17.1"
                - "1.16.5"
                - "1.16.4"
        validations:
            required: true
    -   type: input
        attributes:
            label: Loader Version
            description: The version of Forge or Fabric you were using when the bug occured
            placeholder: Forge 39.0.0
        validations:
            required: true
    -   type: textarea
        attributes:
            label: Other Mods
            description: Please list any other mods that were running when the crash happened
        validations:
            required: false
    -   type: textarea
        attributes:
            label: Additional Context
            description: Add any extra context about the bug here
        validations:
            required: false
    -   type: markdown
        attributes:
            value: "Thank you for taking the time to make this bug report and to help improve Flywheel"
