package com.jozufozu.flywheel.api.event;

public enum RenderStage {
	BEFORE_SKY,
	AFTER_SKY,
	BEFORE_TERRAIN,
	AFTER_SOLID_TERRAIN,
	BEFORE_ENTITIES,
	AFTER_ENTITIES,
	AFTER_BLOCK_ENTITIES,
	BEFORE_CRUMBLING,
	AFTER_FINAL_END_BATCH,
	AFTER_TRANSLUCENT_TERRAIN,
	AFTER_PARTICLES,
	AFTER_WEATHER;
}
